kind: Service
apiVersion: v1
metadata:
  name: todo-backend
spec:
  selector:
    app: todo-backend
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 31313
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  selector:
    matchLabels:
      app: todo-backend
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: todo-backend
        tier: backend
    spec:
      containers:
        - image: v4ler4/spring-boot-docker
          name: todo-backend
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE_URL
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER